/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wallet;
import java.awt.CardLayout;
import com.placeholder.PlaceHolder;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.Security;
import java.security.spec.InvalidKeySpecException;
import java.util.*;

import wallet.LoginPage;
import com.dottorsoft.SimpleBlockChain.core.Block;
import com.dottorsoft.SimpleBlockChain.core.Transaction;
import com.dottorsoft.SimpleBlockChain.core.TransactionOutput;
import com.dottorsoft.SimpleBlockChain.core.Wallet;
import com.dottorsoft.SimpleBlockChain.networking.ExecuteCommands;
import com.dottorsoft.SimpleBlockChain.util.ChainUtils;
import com.dottorsoft.SimpleBlockChain.util.Parameters;
import com.dottorsoft.SimpleBlockChain.util.StringUtil;
import com.google.gson.*;
import com.google.gson.reflect.TypeToken;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class CDClientUI extends javax.swing.JFrame {
    PlaceHolder holder;
    //public static String ipAddress;
    //public static HashMap<String,TransactionOutput> UTXOs = new HashMap<String,TransactionOutput>();
    public static float minimumTransaction = 0.1f;
    public static Wallet walletA;
    //public static Wallet walletB = new Wallet();
    public static Transaction genesisTransaction;
    public static ExecuteCommands server; //= new ExecuteCommands(8888);
    public static ExecuteCommands client; //= new ExecuteCommands(8889);
    /**
     * Creates new form CDClientUI
     */
    public CDClientUI() {
        initComponents();
        holder = new PlaceHolder(payToTextField, "Enter a CryptoDinero address (e.g. 2EE57059EE6D2AD31EADB385C2282D342971B308AE418)");
        holder = new PlaceHolder(labelTextField, "Enter a label for this address to label the transaction");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overviewBtn = new javax.swing.JButton();
        sendBtn = new javax.swing.JButton();
        receiveBtn = new javax.swing.JButton();
        transactionBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        overviewPanel = new javax.swing.JPanel();
        walletPanel = new javax.swing.JPanel();
        balanceLabel = new javax.swing.JLabel();
        unconfirmedLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        balanceCoins = new javax.swing.JLabel();
        unconfirmedCoins = new javax.swing.JLabel();
        transactionCount = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sendPanel = new javax.swing.JPanel();
        payLabel = new javax.swing.JLabel();
        payToTextField = new javax.swing.JTextField();
        labelLabel = new javax.swing.JLabel();
        labelTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        amountSpinner = new javax.swing.JSpinner();
        sendCoinBtn = new javax.swing.JButton();
        receivePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        transactionPanel = new javax.swing.JPanel();
        recentPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lab = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CryptoDinero");

        overviewBtn.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        overviewBtn.setText("Overview");
        overviewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewBtnActionPerformed(evt);
            }
        });

        sendBtn.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        sendBtn.setText("Send Coins");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        receiveBtn.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        receiveBtn.setText("Receive Coins");
        receiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveBtnActionPerformed(evt);
            }
        });

        transactionBtn.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        transactionBtn.setText("Transactions");
        transactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionBtnActionPerformed(evt);
            }
        });

        mainPanel.setLayout(new java.awt.CardLayout());

        walletPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Wallet", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        walletPanel.setName("Wallet"); // NOI18N

        balanceLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        balanceLabel.setText("Balance:");

        unconfirmedLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        unconfirmedLabel.setText("Unconfirmed:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Number of Transactions:");

        balanceCoins.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        balanceCoins.setText("00.000 CD");

        unconfirmedCoins.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        unconfirmedCoins.setText("00.000 CD");

        transactionCount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        transactionCount.setText("0");

        javax.swing.GroupLayout walletPanelLayout = new javax.swing.GroupLayout(walletPanel);
        walletPanel.setLayout(walletPanelLayout);
        walletPanelLayout.setHorizontalGroup(
            walletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(walletPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(walletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(unconfirmedLabel)
                    .addComponent(balanceLabel))
                .addGap(18, 18, 18)
                .addGroup(walletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceCoins)
                    .addComponent(unconfirmedCoins)
                    .addComponent(transactionCount))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        walletPanelLayout.setVerticalGroup(
            walletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(walletPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(walletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceLabel)
                    .addComponent(balanceCoins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(walletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unconfirmedLabel)
                    .addComponent(unconfirmedCoins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(walletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(transactionCount))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Your PK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout overviewPanelLayout = new javax.swing.GroupLayout(overviewPanel);
        overviewPanel.setLayout(overviewPanelLayout);
        overviewPanelLayout.setHorizontalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPanelLayout.createSequentialGroup()
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overviewPanelLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(updateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(overviewPanelLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(walletPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        overviewPanelLayout.setVerticalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overviewPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(walletPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        mainPanel.add(overviewPanel, "overviewPanel");

        sendPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        payLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        payLabel.setText("Pay To:");

        payToTextField.setToolTipText("");
        payToTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                payToTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                payToTextFieldFocusLost(evt);
            }
        });
        payToTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payToTextFieldActionPerformed(evt);
            }
        });

        labelLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLabel.setText("Label:");

        labelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Amount:");

        sendCoinBtn.setText("Send");
        sendCoinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendCoinBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sendPanelLayout = new javax.swing.GroupLayout(sendPanel);
        sendPanel.setLayout(sendPanelLayout);
        sendPanelLayout.setHorizontalGroup(
            sendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(sendPanelLayout.createSequentialGroup()
                        .addComponent(payLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(payToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sendPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelTextField))
                    .addGroup(sendPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendCoinBtn)
                            .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        sendPanelLayout.setVerticalGroup(
            sendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payLabel)
                    .addComponent(payToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLabel)
                    .addComponent(labelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(sendCoinBtn)
                .addGap(38, 38, 38))
        );

        mainPanel.add(sendPanel, "sendPanel");

        jLabel4.setText("Receiving Address: ");

        jLabel5.setText("Message Receieved: ");

        jLabel6.setText("Requested Amount:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Save");

        javax.swing.GroupLayout receivePanelLayout = new javax.swing.GroupLayout(receivePanel);
        receivePanel.setLayout(receivePanelLayout);
        receivePanelLayout.setHorizontalGroup(
            receivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receivePanelLayout.createSequentialGroup()
                .addGroup(receivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receivePanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(receivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(receivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)))
                    .addGroup(receivePanelLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jButton1)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        receivePanelLayout.setVerticalGroup(
            receivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receivePanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(receivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(receivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(receivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        mainPanel.add(receivePanel, "receivePanel");

        recentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Recent Transactions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lab.setColumns(20);
        lab.setRows(5);
        jScrollPane1.setViewportView(lab);

        javax.swing.GroupLayout recentPanelLayout = new javax.swing.GroupLayout(recentPanel);
        recentPanel.setLayout(recentPanelLayout);
        recentPanelLayout.setHorizontalGroup(
            recentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
        recentPanelLayout.setVerticalGroup(
            recentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transactionPanelLayout = new javax.swing.GroupLayout(transactionPanel);
        transactionPanel.setLayout(transactionPanelLayout);
        transactionPanelLayout.setHorizontalGroup(
            transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionPanelLayout.createSequentialGroup()
                .addGroup(transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionPanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(recentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transactionPanelLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jButton3)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        transactionPanelLayout.setVerticalGroup(
            transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(recentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(24, 24, 24))
        );

        mainPanel.add(transactionPanel, "transactionPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(overviewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(receiveBtn)
                        .addGap(18, 18, 18)
                        .addComponent(transactionBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(overviewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void overviewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewBtnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "overviewPanel");
    }//GEN-LAST:event_overviewBtnActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "sendPanel");
    }//GEN-LAST:event_sendBtnActionPerformed

    private void receiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveBtnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "receivePanel");
    }//GEN-LAST:event_receiveBtnActionPerformed

    private void transactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionBtnActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "transactionPanel");
    }//GEN-LAST:event_transactionBtnActionPerformed

    private void labelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelTextFieldActionPerformed

    private void payToTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payToTextFieldActionPerformed
        
    }//GEN-LAST:event_payToTextFieldActionPerformed

    private void payToTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_payToTextFieldFocusGained
        //payToTextField.setText("");
    }//GEN-LAST:event_payToTextFieldFocusGained

    private void payToTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_payToTextFieldFocusLost
        //payToTextField.setText("Enter a CryptoDinero address (e.g. fjk1hk4kaj)");
    }//GEN-LAST:event_payToTextFieldFocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void sendCoinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendCoinBtnActionPerformed
        // TODO add your handling code here:
        Gson gson = new Gson();
//        /////////////////////////////////////////////////////////////server.getTransaction()
        LinkedHashMap<String, Block> netParamBlockchain = gson.fromJson(server.getTransaction(), new TypeToken<LinkedHashMap<String, Block>>() {}.getType());
        if(netParamBlockchain.size() > Parameters.blockchain.size())
        {
            Parameters.blockchain = netParamBlockchain;
        }
        
        try {
            amountSpinner.commitEdit();
        } catch ( java.text.ParseException e ) { System.out.println("wrong number"); }
        int value = (Integer) amountSpinner.getValue();
        float newVal = (float) value;
        
        LinkedHashMap<String, Block> temp = Parameters.blockchain;
        Set set = temp.entrySet();
        Iterator iterator = set.iterator();
        Block tempBlock = null;
        
        while(iterator.hasNext())
        {
                Map.Entry item = (Map.Entry) iterator.next();
                //System.out.println("Key = " + item.getKey() + " Value = " + item.getValue());
                tempBlock = (Block) item.getValue();
                //System.out.println(p.getHash());
                String lastBlockHash = tempBlock.getHash();
                tempBlock = new Block(lastBlockHash);
        }    
        try {
            tempBlock.addTransaction(walletA.sendFunds(payToTextField.getText(), newVal));
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(CDClientUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeySpecException ex) {
            Logger.getLogger(CDClientUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchProviderException ex) {
            Logger.getLogger(CDClientUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        addBlock(tempBlock.getHash(),tempBlock);
        System.out.println(StringUtil.getJson(Parameters.UTXOs));
        /////////////////////////////////////////////////////////////server.getTransaction()
//        temp = Parameters.blockchain;
//        set = temp.entrySet();
//        iterator = set.iterator();
//        while(iterator.hasNext())
//        {
//                Map.Entry item = (Map.Entry) iterator.next();
//                //System.out.println("Key = " + item.getKey() + " Value = " + item.getValue());
//                tempBlock = (Block) item.getValue();
//                //System.out.println(p.getHash());
//                System.out.println(tempBlock);
//        }
        server.connect(LoginPage.ipAddress, 8888);
    }//GEN-LAST:event_sendCoinBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        
        Gson gson = new Gson();
        /////////////////////////////////////////////////////////////server.getTransaction()
        LinkedHashMap<String, TransactionOutput> netParamUTXOs = gson.fromJson(server.getTransaction(), new TypeToken<LinkedHashMap<String, TransactionOutput>>() {}.getType());
        System.out.println("Net: " + netParamUTXOs.size() + "\nActual: " + Parameters.UTXOs.size());
        if(netParamUTXOs.size() > Parameters.UTXOs.size())
        {
            Parameters.UTXOs = netParamUTXOs;
            System.out.println(StringUtil.getJson(Parameters.UTXOs));
        }
        balanceCoins.setText(String.valueOf(walletA.getBalance()));
        //transactionCount
//                LinkedHashMap<String, Block> obj = gson.fromJson(server.getBlockChain(), new TypeToken<LinkedHashMap<String, Block>>() {}.getType());
//		if(obj.size() > Parameters.UTXOs.size())
//                {
//                    Parameters.blockchain = obj;
//                    //Parameters.blockchain = new LinkedHashMap<String, Block>();
//                }
//                for (Map.Entry<String, Block> entry : Parameters.blockchain.entrySet()) {
//                    System.out.println(entry.getValue());
//                }
                
       server.connect(LoginPage.ipAddress, 8888);
        /*
        System.out.println("client "+Parameters.UTXOs);
        System.out.println("client " + obj);
        System.out.println(StringUtil.getJson(Parameters.UTXOs));
        System.out.println();

        for (Map.Entry<String, TransactionOutput> entry : Parameters.UTXOs.entrySet()) {
            System.out.println(entry.getValue());
            */
    }//GEN-LAST:event_updateBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, ("Your Public Key is: \nIt has been copied to your clipboard.\n" + walletA.getPublicKey()));
        System.out.println(walletA.getPublicKey());
        StringSelection stringSelection = new StringSelection (walletA.getPublicKey());
        Clipboard clpbrd = Toolkit.getDefaultToolkit ().getSystemClipboard ();
        clpbrd.setContents (stringSelection, null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     Gson gson = new Gson();
     
     LinkedHashMap<String, TransactionOutput> obj = gson.fromJson(StringUtil.getJson(Parameters.UTXOs), new TypeToken<LinkedHashMap<String, TransactionOutput>>() {}.getType());

        String id ="";
        for (Map.Entry<String, TransactionOutput> entry : Parameters.UTXOs.entrySet())
        {  
           if(entry.getValue().reciepient.equals(walletA.getPublicKey()))
           {      
               
            id = id + "ID: " + entry.getValue().id + "\n";
            id = id + "Amount: " + entry.getValue().value+ " CD" + "\n\n";
           } 
        }
        lab.setText(id);
        lab.setEditable(false);
       
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws NoSuchAlgorithmException, InvalidKeySpecException, NoSuchProviderException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CDClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CDClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CDClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CDClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CDClientUI().setVisible(true);
            }
        });
        //add our blocks to the blockchain ArrayList:
		Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider()); //Setup Bouncey castle as a Security Provider
		
		//Create wallets:
		walletA = new Wallet();
                
		Wallet walletB = new Wallet();		
		Wallet wallet = new Wallet();
//              
                //Print transaction ids
                TransactionOutput transactionID = new TransactionOutput();
                
		
		//create genesis transaction, which sends 100 NoobCoin to walletA: 
		genesisTransaction = new Transaction(wallet.getPublicKey(), walletA.getPublicKey(), 100f, null);
		genesisTransaction.generateSignature(wallet.getPrivateKey());	 //manually sign the genesis transaction	
		genesisTransaction.setTransactionId("0"); //manually set the transaction id
		genesisTransaction.getOutputs().add(new TransactionOutput(genesisTransaction.getReciepient(), genesisTransaction.getValue(), genesisTransaction.getTransactionId())); //manually add the Transactions Output
		Parameters.UTXOs.put(genesisTransaction.getOutputs().get(0).id, genesisTransaction.getOutputs().get(0)); //its important to store our first transaction in the UTXOs list.
		
		System.out.println("Creating and Mining Genesis block... ");
		Block genesis = new Block("0");
		genesis.addTransaction(genesisTransaction);
		addBlock(genesis.getHash(),genesis);
		
		//testing
		Block block1 = new Block(genesis.getHash());
		System.out.println("\nWalletA's balance is: " + walletA.getBalance());
		System.out.println("\nWalletA is Attempting to send funds (40) to WalletB...");
		block1.addTransaction(walletA.sendFunds(walletB.getPublicKey(), 40f));
		addBlock(block1.getHash(),block1);
		System.out.println("\nWalletA's balance is: " + walletA.getBalance());
		System.out.println("WalletB's balance is: " + walletB.getBalance());
		
		Block block2 = new Block(block1.getHash());
		System.out.println("\nWalletA Attempting to send more funds (1000) than it has...");
		block2.addTransaction(walletA.sendFunds(walletB.getPublicKey(), 1000f));
		addBlock(block2.getHash(),block2);
		System.out.println("\nWalletA's balance is: " + walletA.getBalance());
		System.out.println("WalletB's balance is: " + walletB.getBalance());
		
		Block block3 = new Block(block2.getHash());
		System.out.println("\nWalletB is Attempting to send funds (20) to WalletA...");
		block3.addTransaction(walletB.sendFunds( walletA.getPublicKey(), 20));
		System.out.println("\nWalletA's balance is: " + walletA.getBalance());
		System.out.println("WalletB's balance is: " + walletB.getBalance());
		addBlock(block3.getHash(),block3);
	
		if(!ChainUtils.isChainValid(Parameters.blockchain, genesisTransaction)){
			System.out.println("Not Valid Chain!!");
			return;
		}
               
                for (Map.Entry<String, Block> entry : Parameters.blockchain.entrySet()) {
                    Block b = entry.getValue();
                    ArrayList<Transaction> t = b.getTransactions();
                    for(Transaction r : t){
                        String trans = r.getReciepient();
                        //System.out.println(trans);
                        
                    }
                    
                    System.out.println();
                    
                }
                
                /*
//                System.out.println("Original Hashes");
//                System.out.println(genesis.getHash() + "\n" +block1.getHash() + "\n" +block2.getHash() + "\n" +block3.getHash());
                System.out.println("\n");
                
                Gson gson = new Gson();
                /////////////////////////////////////////////////////////////server.getTransaction()
                LinkedHashMap<String, TransactionOutput> obj = gson.fromJson(StringUtil.getJson(Parameters.UTXOs), new TypeToken<LinkedHashMap<String, TransactionOutput>>() {}.getType());
		System.out.println("client "+Parameters.UTXOs);
                System.out.println("client " + obj.size());
                System.out.println(StringUtil.getJson(Parameters.UTXOs));
                System.out.println();
                
                for (Map.Entry<String, TransactionOutput> entry : Parameters.UTXOs.entrySet()) {
                    System.out.println(entry.getValue());
                    // now work with key and value...
                }
                //transactionID.showTransactions(walletA.getPublicKey());
		//
		/*String blockchainJson = StringUtil.getJson(Parameters.blockchain);
		System.out.println("\nThe block chain: ");
		System.out.println(blockchainJson);
		
//		ExecuteCommands server = new ExecuteCommands(8888);
//		ExecuteCommands client = new ExecuteCommands(8889);
		//ExecuteCommands client2 = new ExecuteCommands(8890);
                */
                server = new ExecuteCommands(8888);
                client = new ExecuteCommands(8889);
                
		client.connect(LoginPage.ipAddress, 8888);
		//client2.connect("127.0.0.1", 8888);
		System.out.println("RECEIVED: "+client.register());
		//client2.register();
		//server.connect("127.0.0.1", 8890);
		server.connect(LoginPage.ipAddress, 8888);
                
               /*
                Gson gson = new Gson();
                LinkedHashMap<String, Block> obj = gson.fromJson(server.getBlockChain(), new TypeToken<LinkedHashMap<String, Block>>() {}.getType());
		System.out.println("client "+Parameters.blockchain);
                System.out.println("client " + obj);
                Parameters.blockchain = obj;
                if(!ChainUtils.isChainValid(Parameters.blockchain, genesisTransaction)){
			System.out.println("Not Valid Chain!!");
			return;
		}
                */
                
//                client.connect("127.0.0.1", 8888);
//                System.out.println("client "+client.getBlockChainSize());
		
		//server.pingAll();
		//System.out.println("client2"+client2.getBlockChainSize());
		//server.connect("127.0.0.1", 8889);
		
		//System.out.println("server"+server.getBlockChainSize());
		//String chain = client.getBlockChain();
		//System.out.println(chain);
		//System.out.println(client.getBlockChainSize());
		//System.out.println(client2.getBlockChainSize());
		//Block block4 = new Block();
		//ArrayList<Block> c = block4.fromJsonToChain(chain);
		//System.out.println("***************");
		//System.out.println(StringUtil.getJson(c));
        /* Create and display the form */
        
        
    }
    public static void addBlock(String current, Block newBlock) {
		newBlock.mineBlock(Parameters.difficulty);
		Parameters.blockchain.put(current, newBlock);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JLabel balanceCoins;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextArea lab;
    private javax.swing.JLabel labelLabel;
    private javax.swing.JTextField labelTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton overviewBtn;
    private javax.swing.JPanel overviewPanel;
    private javax.swing.JLabel payLabel;
    private javax.swing.JTextField payToTextField;
    private javax.swing.JButton receiveBtn;
    private javax.swing.JPanel receivePanel;
    private javax.swing.JPanel recentPanel;
    private javax.swing.JButton sendBtn;
    private javax.swing.JButton sendCoinBtn;
    private javax.swing.JPanel sendPanel;
    private javax.swing.JButton transactionBtn;
    private javax.swing.JLabel transactionCount;
    private javax.swing.JPanel transactionPanel;
    private javax.swing.JLabel unconfirmedCoins;
    private javax.swing.JLabel unconfirmedLabel;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel walletPanel;
    // End of variables declaration//GEN-END:variables
}
